# Generated by Django 3.2.13 on 2022-04-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220425_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='cat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.category'),
        ),
    ]
