# Generated by Django 3.2.13 on 2022-04-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('Name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
