# Generated by Django 3.2.13 on 2022-05-06 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_customuser_following'),
        ('projects', '0006_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderprocssing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordername', models.CharField(max_length=25, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(max_length=8, null=True)),
                ('order_cond', models.TextField()),
                ('cost', models.BigIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.category')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.freelancer')),
            ],
        ),
    ]
