# Generated by Django 3.2.13 on 2022-05-06 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_customuser_following'),
        ('projects', '0008_finelorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client'),
        ),
    ]
