# Generated by Django 3.2.13 on 2022-05-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_customuser_following'),
        ('projects', '0010_alter_projects_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Freelancer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.freelancer'),
        ),
    ]
