# Generated by Django 3.2.13 on 2022-05-09 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_delete_rating'),
        ('projects', '0011_alter_projects_freelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=8, null=True)),
                ('cost', models.PositiveIntegerField(null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.post')),
                ('usercomment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.freelancer')),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Freelancer',
        ),
        migrations.AddField(
            model_name='projects',
            name='content',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='projects',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='freelancerr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancepro', to='accounts.freelancer'),
        ),
        migrations.AddField(
            model_name='projects',
            name='other',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/projects'),
        ),
        migrations.AddField(
            model_name='projects',
            name='other2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/projects'),
        ),
        migrations.AddField(
            model_name='projects',
            name='other3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/projects'),
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
