# Generated by Django 3.2.13 on 2022-05-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20220509_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finelorder',
            name='rate',
        ),
        migrations.AddField(
            model_name='finelorder',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
