# Generated by Django 3.2.13 on 2022-05-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20220509_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finelorder',
            name='done',
        ),
    ]
