# Generated by Django 3.2.13 on 2022-05-09 23:17

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=creditcards.models.CardNumberField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='payment',
            name='expire',
            field=creditcards.models.CardExpiryField(default=None),
        ),
        migrations.AddField(
            model_name='payment',
            name='security_code',
            field=creditcards.models.SecurityCodeField(default=None, max_length=4),
        ),
    ]
