# Generated by Django 3.2.13 on 2022-05-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_payment_ord_det'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprocssing',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
