# Generated by Django 3.2.13 on 2022-05-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_orderprocssing_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderprocssing',
            name='submit',
        ),
        migrations.AddField(
            model_name='finelorder',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
