# Generated by Django 3.2.13 on 2022-05-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20220516_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprocssing',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
