# Generated by Django 3.2.13 on 2022-05-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_orderprocssing_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finelorder',
            name='submit',
        ),
    ]
