# Generated by Django 3.2.13 on 2022-05-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_orderprocssing_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finelorder',
            name='oredrp',
            field=models.FileField(upload_to='media/orders', verbose_name='order'),
        ),
    ]
