# Generated by Django 3.2.13 on 2022-05-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_comment_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprocssing',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
