# Generated by Django 3.2.13 on 2022-05-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_orderprocssing_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='date',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
