# Generated by Django 3.2.13 on 2022-04-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=b'I01\n', null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='slug',
            field=models.SlugField(blank=b'I01\n', null=True),
        ),
    ]
