# Generated by Django 3.2.13 on 2022-04-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220424_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='slug',
        ),
    ]
