# Generated by Django 3.2.13 on 2022-04-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Profileimg',
            field=models.ImageField(blank=True, default='img/default.jpg', upload_to='profile_pics'),
        ),
    ]
