# Generated by Django 3.2.13 on 2022-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='banckacc',
        ),
        migrations.AddField(
            model_name='customuser',
            name='banckacc',
            field=models.PositiveBigIntegerField(max_length=15, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
