# Generated by Django 3.2.13 on 2022-04-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220425_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='banckacc',
            field=models.PositiveBigIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
