# Generated by Django 3.2.13 on 2022-04-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_banckacc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='banckacc',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
