# Generated by Django 3.2.13 on 2022-04-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_skills'),
        ('accounts', '0011_freelancer_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='cat',
            field=models.ManyToManyField(blank=True, default='null', to='projects.Category'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(blank=True, default='null', to='projects.skills'),
        ),
    ]
