# Generated by Django 3.2.13 on 2022-04-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_skills'),
        ('accounts', '0013_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='cat',
            field=models.ManyToManyField(blank=True, default='null', related_name='ca', to='projects.Category'),
        ),
    ]
