# Generated by Django 3.2.13 on 2022-04-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_freelancer_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='cat',
        ),
    ]
