# Generated by Django 3.2.13 on 2022-04-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_skills'),
        ('accounts', '0015_remove_freelancer_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='cat',
            field=models.ManyToManyField(blank=True, default='null', related_name='ca', to='projects.Category'),
        ),
    ]
