# Generated by Django 3.2.13 on 2022-04-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_freelancer_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='cat',
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
