# Generated by Django 3.2.13 on 2022-05-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_customuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='muted',
        ),
    ]
