# Generated by Django 3.2.13 on 2022-05-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Follow'),
        ),
    ]
