# Generated by Django 3.2.13 on 2022-05-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20220508_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rating',
        ),
    ]
