# Generated by Django 3.2.13 on 2022-05-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.chat', verbose_name='Chat'),
        ),
    ]
