# Generated by Django 3.2.13 on 2022-05-13 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_massage_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='sender',
        ),
        migrations.AddField(
            model_name='massage',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='massage',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='Readed'),
        ),
    ]
