# Generated by Django 3.2.13 on 2022-05-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20220514_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massage',
            old_name='reciever',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='sender',
        ),
    ]
