# Generated by Django 3.2.13 on 2022-05-14 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_chats_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='user',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='sender',
        ),
        migrations.AddField(
            model_name='chats',
            name='sender',
            field=models.ManyToManyField(default=None, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
