# Generated by Django 3.2.13 on 2022-05-14 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20220514_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='sender',
        ),
        migrations.AddField(
            model_name='chats',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='chats',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Massage'),
        ),
        migrations.AddField(
            model_name='massage',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
