# Generated by Django 3.2.13 on 2022-05-14 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_chats_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='reciever',
        ),
        migrations.AddField(
            model_name='massage',
            name='reciever',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL),
        ),
    ]
