# Generated by Django 3.2.13 on 2022-05-14 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20220514_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='Messages',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='name',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='sender',
        ),
        migrations.AddField(
            model_name='chats',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='massage',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
