# Generated by Django 3.2.13 on 2022-05-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20220514_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
