# Generated by Django 3.2.13 on 2022-05-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_rateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='Readed'),
        ),
    ]
