# Generated by Django 3.2.13 on 2022-05-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateprofile',
            name='sub',
            field=models.BooleanField(default=False),
        ),
    ]
