# Generated by Django 3.2.13 on 2022-05-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_customuser_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rate',
        ),
    ]
