# Generated by Django 3.2.13 on 2022-05-20 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_remove_customuser_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='contuctus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outside_user', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(default='دعم', max_length=20)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needhelp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
